//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeAmigos_ExpenseManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ExpenseReport
    {
        public ExpenseReport()
        {
            this.ExpenseItems = new HashSet<ExpenseItem>();
        }
    
        public int ExpenseId { get; set; }        
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public int CreatedById { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<int> ProcessedById { get; set; }
        public string Status { get; set; }
        public int ExpenseToDept { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee ApprovedBy { get; set; }
        public virtual Employee ProcessedBy { get; set; }
        public virtual Employee CreatedBy { get; set; }
        public virtual ICollection<ExpenseItem> ExpenseItems { get; set; }
    }
}
